name: 15 - Working with Matrix

on:
    workflow_dispatch:

jobs:
    backwords-compatibility:
        name: ${{ matrix.os-version }} - ${{ matrix.node-version }}
        runs-on: ${{ matrix.os-version }}
        strategy:
            matrix:
                node-version: [18.x, 20.x, 22.x]
                os-version:
                    - ubuntu-latest
                    - windows-latest
                    - macos-latest
        steps:
            - name: Setup Node
              uses: actions/setup-node@v4
              with: ${{ matrix.node-version }}
            - name: Perform some tests
              run: echo "Running tests on OS: ${{ matrix.os-version }} and NodeJS: ${{ matrix.node-version }}"
